// Generated by the Crawlora platform client generator. Do not edit.
export const operations = {
  "tiktok-category": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "tiktok-category",
    "method": "GET",
    "path": "/tiktok/category",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "tiktok-challenge": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "tiktok-challenge",
    "method": "GET",
    "path": "/tiktok/hashtag/{name}",
    "pathParams": [
      "name"
    ],
    "produces": [
      "application/json"
    ],
    "queryParams": [],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "tiktok-challenge-list": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "cursorParams": [
      "cursor"
    ],
    "formParams": [],
    "id": "tiktok-challenge-list",
    "method": "GET",
    "paginatable": true,
    "path": "/tiktok/hashtags",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "cursor",
        "type": "integer"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "tiktok-creative-center-hashtags": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "tiktok-creative-center-hashtags",
    "method": "GET",
    "path": "/tiktok/creative-center/hashtags",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "country_code",
        "required": true,
        "type": "string"
      },
      {
        "enum": [
          "7",
          "30"
        ],
        "in": "query",
        "name": "period",
        "type": "integer"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "tiktok-creative-center-videos": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "tiktok-creative-center-videos",
    "method": "GET",
    "path": "/tiktok/creative-center/videos",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "country_code",
        "required": true,
        "type": "string"
      },
      {
        "enum": [
          "7",
          "30"
        ],
        "in": "query",
        "name": "period",
        "type": "integer"
      },
      {
        "enum": [
          "views",
          "engagement",
          "six_second_views"
        ],
        "in": "query",
        "name": "sort_by",
        "type": "string"
      },
      {
        "in": "query",
        "name": "content_label_id",
        "type": "string"
      },
      {
        "in": "query",
        "name": "organic_only",
        "type": "boolean"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "tiktok-explore": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "tiktok-explore",
    "method": "GET",
    "path": "/tiktok/explore/{id}",
    "pathParams": [
      "id"
    ],
    "produces": [
      "application/json"
    ],
    "queryParams": [],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "tiktok-popular-trend-country-industry-meta": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "tiktok-popular-trend-country-industry-meta",
    "method": "GET",
    "path": "/tiktok/popular-trend/country-industry-meta",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "tiktok-post": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "tiktok-post",
    "method": "GET",
    "path": "/tiktok/post/{id}",
    "pathParams": [
      "id"
    ],
    "produces": [
      "application/json"
    ],
    "queryParams": [],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "tiktok-profile": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "tiktok-profile",
    "method": "GET",
    "path": "/tiktok/profile/{handler}",
    "pathParams": [
      "handler"
    ],
    "produces": [
      "application/json"
    ],
    "queryParams": [],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "tiktok-profile-post": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "cursorParams": [
      "cursor"
    ],
    "formParams": [],
    "id": "tiktok-profile-post",
    "method": "GET",
    "paginatable": true,
    "path": "/tiktok/posts",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "secUid",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "cursor",
        "type": "integer"
      },
      {
        "enum": [
          "0",
          "1",
          "2"
        ],
        "in": "query",
        "name": "sort_type",
        "type": "integer"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "tiktok-search": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "cursorParams": [
      "cursor"
    ],
    "formParams": [],
    "id": "tiktok-search",
    "method": "GET",
    "paginatable": true,
    "path": "/tiktok/search",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "keyword",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "cursor",
        "type": "integer"
      },
      {
        "in": "query",
        "name": "count",
        "type": "integer"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "tiktok-search-hashtag": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "cursorParams": [
      "cursor"
    ],
    "formParams": [],
    "id": "tiktok-search-hashtag",
    "method": "GET",
    "paginatable": true,
    "path": "/tiktok/search/hashtag",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "keyword",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "cursor",
        "type": "integer"
      },
      {
        "in": "query",
        "name": "count",
        "type": "integer"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "tiktok-search-user": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "cursorParams": [
      "cursor"
    ],
    "formParams": [],
    "id": "tiktok-search-user",
    "method": "GET",
    "paginatable": true,
    "path": "/tiktok/search/user",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "keyword",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "cursor",
        "type": "integer"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "tiktok-top-ads-analysis": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "tiktok-top-ads-analysis",
    "method": "GET",
    "path": "/tiktok/top-ads/analysis",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "material_id",
        "required": true,
        "type": "string"
      },
      {
        "enum": [
          "retain_ctr",
          "retain_cvr",
          "click_cnt",
          "convert_cnt",
          "play_retain_cnt"
        ],
        "in": "query",
        "name": "metric",
        "type": "string"
      },
      {
        "enum": [
          "7",
          "30",
          "180"
        ],
        "in": "query",
        "name": "period_type",
        "type": "integer"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "tiktok-top-ads-detail": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "tiktok-top-ads-detail",
    "method": "GET",
    "path": "/tiktok/top-ads/detail",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "material_id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "tiktok-top-ads-filters": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "tiktok-top-ads-filters",
    "method": "GET",
    "path": "/tiktok/top-ads/filters",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "tiktok-top-ads-list": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "tiktok-top-ads-list",
    "method": "GET",
    "paginatable": true,
    "path": "/tiktok/top-ads/list",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "enum": [
          "7",
          "30",
          "180"
        ],
        "in": "query",
        "name": "period",
        "type": "integer"
      },
      {
        "in": "query",
        "name": "page",
        "type": "integer"
      },
      {
        "in": "query",
        "name": "limit",
        "type": "integer"
      },
      {
        "enum": [
          "for_you",
          "impression",
          "ctr",
          "play_2s_rate",
          "play_6s_rate",
          "cvr",
          "like"
        ],
        "in": "query",
        "name": "order_by",
        "type": "string"
      },
      {
        "in": "query",
        "name": "country_code",
        "type": "string"
      },
      {
        "in": "query",
        "name": "keyword",
        "type": "string"
      },
      {
        "in": "query",
        "name": "industry",
        "type": "string"
      },
      {
        "in": "query",
        "name": "objective",
        "type": "string"
      },
      {
        "in": "query",
        "name": "ad_language",
        "type": "string"
      },
      {
        "in": "query",
        "name": "pattern_label",
        "type": "string"
      },
      {
        "enum": [
          "time-2",
          "time-3",
          "time-4",
          "time-5",
          "time-6",
          "time-7"
        ],
        "in": "query",
        "name": "duration",
        "type": "string"
      },
      {
        "enum": [
          "1",
          "2",
          "3",
          "4",
          "5"
        ],
        "in": "query",
        "name": "like",
        "type": "string"
      },
      {
        "enum": [
          "1",
          "2"
        ],
        "in": "query",
        "name": "ad_format",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "tiktok-top-ads-location-info": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "tiktok-top-ads-location-info",
    "method": "GET",
    "path": "/tiktok/top-ads/location-info",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "module",
        "type": "integer"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "tiktok-top-ads-locations": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "tiktok-top-ads-locations",
    "method": "GET",
    "path": "/tiktok/top-ads/locations",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "tiktok-top-ads-recommend": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "tiktok-top-ads-recommend",
    "method": "GET",
    "paginatable": true,
    "path": "/tiktok/top-ads/recommend",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "material_id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "page",
        "type": "integer"
      },
      {
        "in": "query",
        "name": "limit",
        "type": "integer"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "tiktok-top-ads-safety": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "tiktok-top-ads-safety",
    "method": "GET",
    "path": "/tiktok/top-ads/safety",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "tiktok-top-ads-spotlight": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "tiktok-top-ads-spotlight",
    "method": "GET",
    "paginatable": true,
    "path": "/tiktok/top-ads/spotlight",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "page",
        "type": "integer"
      },
      {
        "in": "query",
        "name": "limit",
        "type": "integer"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "tiktok-top-ads-suggestions": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "tiktok-top-ads-suggestions",
    "method": "GET",
    "path": "/tiktok/top-ads/suggestions",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "count",
        "type": "integer"
      },
      {
        "in": "query",
        "name": "scenario",
        "type": "integer"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "tiktok-trending": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "tiktok-trending",
    "method": "GET",
    "path": "/tiktok/trending",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "tiktok-video-comments": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "cursorParams": [
      "cursor"
    ],
    "formParams": [],
    "id": "tiktok-video-comments",
    "method": "GET",
    "paginatable": true,
    "path": "/tiktok/comments",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "aweme_id",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "cursor",
        "type": "integer"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  }
};

export const groups = {
  "tiktok": {
    "category": "tiktok-category",
    "challenge": "tiktok-challenge",
    "challengeList": "tiktok-challenge-list",
    "creativeCenterHashtags": "tiktok-creative-center-hashtags",
    "creativeCenterVideos": "tiktok-creative-center-videos",
    "explore": "tiktok-explore",
    "popularTrendCountryIndustryMeta": "tiktok-popular-trend-country-industry-meta",
    "post": "tiktok-post",
    "profile": "tiktok-profile",
    "profilePost": "tiktok-profile-post",
    "search": "tiktok-search",
    "searchHashtag": "tiktok-search-hashtag",
    "searchUser": "tiktok-search-user",
    "topAdsAnalysis": "tiktok-top-ads-analysis",
    "topAdsDetail": "tiktok-top-ads-detail",
    "topAdsFilters": "tiktok-top-ads-filters",
    "topAdsList": "tiktok-top-ads-list",
    "topAdsLocationInfo": "tiktok-top-ads-location-info",
    "topAdsLocations": "tiktok-top-ads-locations",
    "topAdsRecommend": "tiktok-top-ads-recommend",
    "topAdsSafety": "tiktok-top-ads-safety",
    "topAdsSpotlight": "tiktok-top-ads-spotlight",
    "topAdsSuggestions": "tiktok-top-ads-suggestions",
    "trending": "tiktok-trending",
    "videoComments": "tiktok-video-comments"
  }
};

export const operationCount = 25;

export const OperationIds = Object.freeze({
  "TiktokCategory": "tiktok-category",
  "TiktokChallenge": "tiktok-challenge",
  "TiktokChallengeList": "tiktok-challenge-list",
  "TiktokCreativeCenterHashtags": "tiktok-creative-center-hashtags",
  "TiktokCreativeCenterVideos": "tiktok-creative-center-videos",
  "TiktokExplore": "tiktok-explore",
  "TiktokPopularTrendCountryIndustryMeta": "tiktok-popular-trend-country-industry-meta",
  "TiktokPost": "tiktok-post",
  "TiktokProfile": "tiktok-profile",
  "TiktokProfilePost": "tiktok-profile-post",
  "TiktokSearch": "tiktok-search",
  "TiktokSearchHashtag": "tiktok-search-hashtag",
  "TiktokSearchUser": "tiktok-search-user",
  "TiktokTopAdsAnalysis": "tiktok-top-ads-analysis",
  "TiktokTopAdsDetail": "tiktok-top-ads-detail",
  "TiktokTopAdsFilters": "tiktok-top-ads-filters",
  "TiktokTopAdsList": "tiktok-top-ads-list",
  "TiktokTopAdsLocationInfo": "tiktok-top-ads-location-info",
  "TiktokTopAdsLocations": "tiktok-top-ads-locations",
  "TiktokTopAdsRecommend": "tiktok-top-ads-recommend",
  "TiktokTopAdsSafety": "tiktok-top-ads-safety",
  "TiktokTopAdsSpotlight": "tiktok-top-ads-spotlight",
  "TiktokTopAdsSuggestions": "tiktok-top-ads-suggestions",
  "TiktokTrending": "tiktok-trending",
  "TiktokVideoComments": "tiktok-video-comments"
});
