// Generated by scripts/generate.py. Do not edit manually.

export type CrawloraResponse<T = unknown> = T;
export type CrawloraBody<T = Record<string, unknown>> = T;

export interface ModelAppResponse {
  "code"?: number;
  "data"?: unknown;
  "msg"?: unknown;
}

export interface ModelTiktokTrendingResponseDoc {
  "code"?: number;
  "data"?: ModelTiktokTrendingResp;
  "msg"?: string;
}

export interface ModelTiktokTrendingResp {
  "cursor"?: string;
  "extra"?: { "fatal_item_ids"?: Array<unknown>; "logid"?: string; "now"?: number };
  "hasMore"?: boolean;
  "itemList"?: Array<unknown>;
  "log_pb"?: { "impr_id"?: string };
  "statusCode"?: number;
  "statusMsg"?: string;
  "status_code"?: number;
  "status_msg"?: string;
  "trendingTopics"?: Array<unknown>;
}

export interface ModelPopulartrendTopAdsSuggestionsResponseDoc {
  "code"?: number;
  "data"?: ModelPopularTrendTopAdsSuggestionsResp;
  "msg"?: string;
}

export interface ModelPopularTrendTopAdsSuggestionsResp {
  "code"?: number;
  "data"?: { "query"?: Array<string> };
  "msg"?: string;
  "request_id"?: string;
}

export interface ModelPopulartrendTopAdsSpotlightResponseDoc {
  "code"?: number;
  "data"?: ModelPopularTrendTopAdsSpotlightResp;
  "msg"?: string;
}

export interface ModelPopularTrendTopAdsSpotlightResp {
  "code"?: number;
  "data"?: { "materials"?: Array<ModelPopularTrendTopAdsMaterial>; "pagination"?: ModelPopularTrendTopAdsPagination };
  "msg"?: string;
  "request_id"?: string;
}

export interface ModelPopularTrendTopAdsPagination {
  "has_more"?: boolean;
  "page"?: number;
  "size"?: number;
  "total"?: number;
  "total_count"?: number;
}

export interface ModelPopularTrendTopAdsMaterial {
  "ad_title"?: string;
  "brand_name"?: string;
  "comment"?: number;
  "cost"?: number;
  "country_code"?: Array<string>;
  "ctr"?: number;
  "favorite"?: boolean;
  "has_summary"?: boolean;
  "highlight"?: string;
  "highlight_text"?: string;
  "id"?: string;
  "industry_key"?: string;
  "is_search"?: boolean;
  "keyword_list"?: Array<string>;
  "landing_page"?: string;
  "like"?: number;
  "objective_key"?: string;
  "objectives"?: Array<ModelPopularTrendTopAdsFilterItem>;
  "pattern_label"?: Array<ModelPopularTrendTopAdsFilterItem>;
  "share"?: number;
  "source"?: string;
  "source_key"?: number;
  "video_info"?: ModelPopularTrendTopAdsVideoInfo;
  "voice_over"?: boolean;
}

export interface ModelPopularTrendTopAdsVideoInfo {
  "cover"?: string;
  "duration"?: number;
  "height"?: number;
  "vid"?: string;
  "video_url"?: Record<string, string>;
  "width"?: number;
}

export interface ModelPopularTrendTopAdsFilterItem {
  "has_conversion"?: boolean;
  "id"?: Record<string, unknown>;
  "label"?: string;
  "parent_id"?: Record<string, unknown>;
  "value"?: string;
}

export interface ModelPopulartrendTopAdsSafetyResponseDoc {
  "code"?: number;
  "data"?: ModelPopularTrendTopAdsSafetyResp;
  "msg"?: string;
}

export interface ModelPopularTrendTopAdsSafetyResp {
  "code"?: number;
  "data"?: { "cc_banner_key"?: string; "creator_search"?: number; "hashtag_search"?: number; "keyword_search"?: number; "sound_search"?: number; "top_ads_search"?: number };
  "msg"?: string;
  "request_id"?: string;
}

export interface ModelPopulartrendTopAdsRecommendResponseDoc {
  "code"?: number;
  "data"?: ModelPopularTrendTopAdsRecommendResp;
  "msg"?: string;
}

export interface ModelPopularTrendTopAdsRecommendResp {
  "code"?: number;
  "data"?: { "materials"?: Array<ModelPopularTrendTopAdsMaterial> };
  "msg"?: string;
  "request_id"?: string;
}

export interface ModelPopulartrendTopAdsLocationsResponseDoc {
  "code"?: number;
  "data"?: ModelPopularTrendTopAdsLocationsResp;
  "msg"?: string;
}

export interface ModelPopularTrendTopAdsLocationsResp {
  "code"?: number;
  "data"?: { "country"?: Array<ModelPopularTrendTopAdsFilterItem> };
  "msg"?: string;
  "request_id"?: string;
}

export interface ModelPopulartrendTopAdsLocationInfoResponseDoc {
  "code"?: number;
  "data"?: ModelPopularTrendTopAdsLocationInfoResp;
  "msg"?: string;
}

export interface ModelPopularTrendTopAdsLocationInfoResp {
  "code"?: number;
  "data"?: { "first_industry"?: Record<string, unknown>; "initial_country"?: Array<string>; "l1_industry"?: number; "l2_industry"?: number; "second_industry"?: Record<string, unknown> };
  "msg"?: string;
  "request_id"?: string;
}

export interface ModelPopulartrendTopAdsListResponseDoc {
  "code"?: number;
  "data"?: ModelPopularTrendTopAdsListResp;
  "msg"?: string;
}

export interface ModelPopularTrendTopAdsListResp {
  "code"?: number;
  "data"?: { "materials"?: Array<ModelPopularTrendTopAdsMaterial>; "pagination"?: ModelPopularTrendTopAdsPagination };
  "msg"?: string;
  "request_id"?: string;
}

export interface ModelPopulartrendTopAdsFiltersResponseDoc {
  "code"?: number;
  "data"?: ModelPopularTrendTopAdsFiltersResp;
  "msg"?: string;
}

export interface ModelPopularTrendTopAdsFiltersResp {
  "code"?: number;
  "data"?: { "ad_format"?: Array<ModelPopularTrendTopAdsFilterItem>; "ad_language"?: Array<ModelPopularTrendTopAdsFilterItem>; "analysis_metric"?: Array<ModelPopularTrendTopAdsFilterItem>; "country"?: Array<ModelPopularTrendTopAdsFilterItem>; "duration"?: Array<ModelPopularTrendTopAdsFilterItem>; "industry"?: Array<ModelPopularTrendTopAdsFilterItem>; "like"?: Array<ModelPopularTrendTopAdsFilterItem>; "objective"?: Array<ModelPopularTrendTopAdsFilterItem>; "order_by"?: Array<ModelPopularTrendTopAdsFilterItem>; "pattern_label"?: Array<ModelPopularTrendTopAdsFilterItem>; "period"?: Array<ModelPopularTrendTopAdsFilterItem> };
  "msg"?: string;
  "request_id"?: string;
}

export interface ModelPopulartrendTopAdsDetailResponseDoc {
  "code"?: number;
  "data"?: ModelPopularTrendTopAdsDetailResp;
  "msg"?: string;
}

export interface ModelPopularTrendTopAdsDetailResp {
  "code"?: number;
  "data"?: ModelPopularTrendTopAdsMaterial;
  "msg"?: string;
  "request_id"?: string;
}

export interface ModelPopulartrendTopAdsAnalysisResponseDoc {
  "code"?: number;
  "data"?: ModelPopularTrendTopAdsAnalysisResp;
  "msg"?: string;
}

export interface ModelPopularTrendTopAdsAnalysisResp {
  "code"?: number;
  "data"?: { "analysis"?: Array<ModelPopularTrendTopAdsAnalysisPoint>; "duration"?: number; "highlight"?: Array<number>; "metric"?: string; "metric_label"?: string; "percentile"?: number; "percentile_data"?: Record<string, number>; "percentile_metric"?: string; "period_type"?: number };
  "msg"?: string;
  "request_id"?: string;
}

export interface ModelPopularTrendTopAdsAnalysisPoint {
  "second"?: number;
  "value"?: number;
}

export interface ModelTiktokSearchUserResponseDoc {
  "code"?: number;
  "data"?: ModelTiktokSearchUserResp;
  "msg"?: string;
}

export interface ModelTiktokSearchUserResp {
  "challenge_list"?: unknown;
  "cursor"?: number;
  "extra"?: unknown;
  "feedback_type"?: string;
  "global_doodle_config"?: unknown;
  "has_more"?: number;
  "input_keyword"?: string;
  "log_pb"?: { "impr_id"?: string };
  "music_list"?: unknown;
  "qc"?: string;
  "rid"?: string;
  "status_code"?: number;
  "status_msg"?: string;
  "type"?: number;
  "user_list"?: Array<unknown>;
}

export interface ModelTiktokSearchHashtagResponseDoc {
  "code"?: number;
  "data"?: ModelTiktokSearchHashtagResp;
  "msg"?: string;
}

export interface ModelTiktokSearchHashtagResp {
  "challenge_list"?: Array<unknown>;
  "cursor"?: number;
  "extra"?: unknown;
  "has_more"?: number;
  "input_keyword"?: string;
  "log_pb"?: { "impr_id"?: string };
  "music_list"?: unknown;
  "qc"?: string;
  "rid"?: string;
  "status_code"?: number;
  "status_msg"?: string;
  "type"?: number;
  "user_list"?: unknown;
}

export interface ModelTiktokSearchResponseDoc {
  "code"?: number;
  "data"?: ModelTiktokSearchResp;
  "msg"?: string;
}

export interface ModelTiktokSearchResp {
  "cursor"?: number;
  "data"?: Array<unknown>;
  "extra"?: unknown;
  "feedback_type"?: string;
  "has_more"?: number;
  "input_keyword"?: string;
  "itemList"?: Array<unknown>;
  "log_pb"?: { "impr_id"?: string };
  "qc"?: string;
  "rid"?: string;
  "status_code"?: number;
  "status_msg"?: string;
  "type"?: number;
}

export interface ModelTiktokProfileResponseDoc {
  "code"?: number;
  "data"?: ModelTiktokProfile;
  "msg"?: string;
}

export interface ModelTiktokProfile {
  "stats"?: ModelTiktokProfileStats;
  "user"?: ModelTiktokUser;
}

export interface ModelTiktokUser {
  "avatarLarger"?: string;
  "bioLink"?: { "link"?: string };
  "commerceUserInfo"?: { "category"?: string; "commerceUser"?: boolean };
  "createTime"?: number;
  "id"?: string;
  "isOrganization"?: number;
  "language"?: string;
  "nickname"?: string;
  "privateAccount"?: boolean;
  "region"?: string;
  "secUid"?: string;
  "secret"?: boolean;
  "signature"?: string;
  "ttSeller"?: boolean;
  "uniqueId"?: string;
  "verified"?: boolean;
}

export interface ModelTiktokProfileStats {
  "diggCount"?: number;
  "followerCount"?: number;
  "followingCount"?: number;
  "friendCount"?: number;
  "heart"?: number;
  "heartCount"?: number;
  "videoCount"?: number;
}

export interface ModelTiktokProfilePostResponseDoc {
  "code"?: number;
  "data"?: ModelTiktokUserPostLinkResp;
  "msg"?: string;
}

export interface ModelTiktokUserPostLinkResp {
  "cursor"?: string;
  "extra"?: { "fatal_item_ids"?: Array<unknown>; "logid"?: string; "now"?: number };
  "hasMore"?: boolean;
  "itemList"?: Array<unknown>;
  "log_pb"?: { "impr_id"?: string };
  "status_code"?: number;
  "status_msg"?: string;
}

export interface ModelTiktokPostResponseDoc {
  "code"?: number;
  "data"?: ModelTiktokVideoDetailResp;
  "msg"?: string;
}

export interface ModelTiktokVideoDetailResp {
  "extra"?: { "fatal_item_ids"?: Array<unknown>; "logid"?: string; "now"?: number };
  "itemInfo"?: unknown;
  "log_pb"?: { "impr_id"?: string };
  "shareMeta"?: { "desc"?: string; "title"?: string };
  "status_code"?: number;
  "status_msg"?: string;
}

export interface ModelPopulartrendCountryIndustryMetaResponseDoc {
  "code"?: number;
  "data"?: ModelPopularTrendCountryIndustryMeta;
  "msg"?: string;
}

export interface ModelPopularTrendCountryIndustryMeta {
  "country"?: Array<ModelPopularTrendCountryIndustryMetaItem>;
  "industry"?: Array<ModelPopularTrendCountryIndustryMetaItem>;
}

export interface ModelPopularTrendCountryIndustryMetaItem {
  "id"?: string;
  "value"?: string;
}

export interface ModelTiktokChallengeListResponseDoc {
  "code"?: number;
  "data"?: ModelTiktokChallengeListResp;
  "msg"?: string;
}

export interface ModelTiktokChallengeListResp {
  "cursor"?: string;
  "extra"?: { "fatal_item_ids"?: Array<unknown>; "logid"?: string; "now"?: number };
  "hasMore"?: boolean;
  "itemList"?: Array<unknown>;
  "log_pb"?: { "impr_id"?: string };
  "statusCode"?: number;
  "status_code"?: number;
  "status_msg"?: string;
}

export interface ModelTiktokChallengeResponseDoc {
  "code"?: number;
  "data"?: ModelTiktokChallengeDetailResp;
  "msg"?: string;
}

export interface ModelTiktokChallengeDetailResp {
  "challengeInfo"?: unknown;
  "extra"?: { "fatal_item_ids"?: Array<unknown>; "logid"?: string; "now"?: number };
  "log_pb"?: { "impr_id"?: string };
  "shareMeta"?: { "desc"?: string; "title"?: string };
  "statusCode"?: number;
  "status_code"?: number;
  "status_msg"?: string;
}

export interface ModelTiktokExploreResponseDoc {
  "code"?: number;
  "data"?: ModelTiktokExploreResp;
  "msg"?: string;
}

export interface ModelTiktokExploreResp {
  "cursor"?: string;
  "extra"?: { "fatal_item_ids"?: Array<unknown>; "logid"?: string; "now"?: number };
  "hasMore"?: boolean;
  "itemList"?: Array<unknown>;
  "log_pb"?: { "impr_id"?: string };
  "statusCode"?: number;
  "status_code"?: number;
  "status_msg"?: string;
}

export interface ModelCreativecenterTrendingVideosResponseDoc {
  "code"?: number;
  "data"?: ModelCreativecenterTrendingVideosResp;
  "msg"?: string;
}

export interface ModelCreativecenterTrendingVideosResp {
  "page_count"?: number;
  "total_count"?: number;
  "videos"?: Array<ModelCreativecenterTrendingVideo>;
}

export interface ModelCreativecenterTrendingVideo {
  "author_avatar_url"?: string;
  "author_bio"?: string;
  "author_follower_count"?: number;
  "author_handle"?: string;
  "author_id"?: string;
  "author_nickname"?: string;
  "content_tags"?: Array<ModelCreativecenterTrendingVideoContentTag>;
  "content_type"?: number;
  "cover_url"?: string;
  "create_time"?: number;
  "engagement_rate"?: number;
  "engagement_rate_lifetime"?: number;
  "item_id"?: string;
  "organic_video_views"?: number;
  "organic_video_views_lifetime"?: number;
  "six_seconds_vtr"?: number;
  "six_seconds_vtr_lifetime"?: number;
  "title"?: string;
  "video_url"?: string;
  "video_views"?: number;
  "video_views_lifetime"?: number;
}

export interface ModelCreativecenterTrendingVideoContentTag {
  "id"?: string;
  "name"?: string;
}

export interface ModelCreativecenterTrendingHashtagsResponseDoc {
  "code"?: number;
  "data"?: ModelCreativecenterTrendingHashtagsResp;
  "msg"?: string;
}

export interface ModelCreativecenterTrendingHashtagsResp {
  "hashtags"?: Array<ModelCreativecenterTrendingHashtag>;
  "total_count"?: number;
}

export interface ModelCreativecenterTrendingHashtag {
  "hashtag_id"?: string;
  "hashtag_name"?: string;
  "industry_ids"?: Array<number>;
  "popularity_curve"?: Array<ModelCreativecenterHashtagTrendPoint>;
  "publish_count"?: number;
  "rank"?: number;
  "top_creators"?: Array<ModelCreativecenterHashtagTopCreator>;
  "video_views"?: number;
}

export interface ModelCreativecenterHashtagTopCreator {
  "avatar_url"?: string;
  "country_code"?: string;
  "creator_id"?: string;
  "follower_count"?: number;
  "handle"?: string;
  "nickname"?: string;
  "rank"?: number;
  "tiktok_uid"?: string;
}

export interface ModelCreativecenterHashtagTrendPoint {
  "timestamp"?: number;
  "value"?: number;
}

export interface ModelTiktokCommentsResponseDoc {
  "code"?: number;
  "data"?: ModelTiktokCommentResp;
  "msg"?: string;
}

export interface ModelTiktokCommentResp {
  "alias_comment_deleted"?: boolean;
  "comments"?: Array<unknown>;
  "cursor"?: number;
  "extra"?: { "api_debug_info"?: unknown; "fatal_item_ids"?: unknown; "now"?: number };
  "has_filtered_comments"?: number;
  "has_more"?: number;
  "log_pb"?: { "impr_id"?: string };
  "reply_style"?: number;
  "status_code"?: number;
  "status_msg"?: string;
  "top_gifts"?: unknown;
  "total"?: number;
}

export interface ModelTiktokCategoryResponseDoc {
  "code"?: number;
  "data"?: Array<ModelTiktokCategory>;
  "msg"?: string;
}

export interface ModelTiktokCategory {
  "name"?: string;
  "type"?: string;
}

export type TiktokCategoryResponse = CrawloraResponse<ModelTiktokCategoryResponseDoc>;
export interface TiktokCategoryParams {
}

export type TiktokVideoCommentsResponse = CrawloraResponse<ModelTiktokCommentsResponseDoc>;
export interface TiktokVideoCommentsParams {
  "aweme_id": string;
  "cursor"?: number;
}

export type TiktokCreativeCenterHashtagsResponse = CrawloraResponse<ModelCreativecenterTrendingHashtagsResponseDoc>;
export interface TiktokCreativeCenterHashtagsParams {
  "country_code": string;
  "period"?: "7" | "30";
}

export type TiktokCreativeCenterVideosResponse = CrawloraResponse<ModelCreativecenterTrendingVideosResponseDoc>;
export interface TiktokCreativeCenterVideosParams {
  "country_code": string;
  "period"?: "7" | "30";
  "sort_by"?: "views" | "engagement" | "six_second_views";
  "content_label_id"?: string;
  "organic_only"?: boolean;
}

export type TiktokExploreResponse = CrawloraResponse<ModelTiktokExploreResponseDoc>;
export interface TiktokExploreParams {
  "id": number;
}

export type TiktokChallengeResponse = CrawloraResponse<ModelTiktokChallengeResponseDoc>;
export interface TiktokChallengeParams {
  "name": string;
}

export type TiktokChallengeListResponse = CrawloraResponse<ModelTiktokChallengeListResponseDoc>;
export interface TiktokChallengeListParams {
  "id": string;
  "cursor"?: number;
}

export type TiktokPopularTrendCountryIndustryMetaResponse = CrawloraResponse<ModelPopulartrendCountryIndustryMetaResponseDoc>;
export interface TiktokPopularTrendCountryIndustryMetaParams {
}

export type TiktokPostResponse = CrawloraResponse<ModelTiktokPostResponseDoc>;
export interface TiktokPostParams {
  "id": string;
}

export type TiktokProfilePostResponse = CrawloraResponse<ModelTiktokProfilePostResponseDoc>;
export interface TiktokProfilePostParams {
  "secUid": string;
  "cursor"?: number;
  "sort_type"?: "0" | "1" | "2";
}

export type TiktokProfileResponse = CrawloraResponse<ModelTiktokProfileResponseDoc>;
export interface TiktokProfileParams {
  "handler": string;
}

export type TiktokSearchResponse = CrawloraResponse<ModelTiktokSearchResponseDoc>;
export interface TiktokSearchParams {
  "keyword": string;
  "cursor"?: number;
  "count"?: number;
}

export type TiktokSearchHashtagResponse = CrawloraResponse<ModelTiktokSearchHashtagResponseDoc>;
export interface TiktokSearchHashtagParams {
  "keyword": string;
  "cursor"?: number;
  "count"?: number;
}

export type TiktokSearchUserResponse = CrawloraResponse<ModelTiktokSearchUserResponseDoc>;
export interface TiktokSearchUserParams {
  "keyword": string;
  "cursor"?: number;
}

export type TiktokTopAdsAnalysisResponse = CrawloraResponse<ModelPopulartrendTopAdsAnalysisResponseDoc>;
export interface TiktokTopAdsAnalysisParams {
  "material_id": string;
  "metric"?: "retain_ctr" | "retain_cvr" | "click_cnt" | "convert_cnt" | "play_retain_cnt";
  "period_type"?: "7" | "30" | "180";
}

export type TiktokTopAdsDetailResponse = CrawloraResponse<ModelPopulartrendTopAdsDetailResponseDoc>;
export interface TiktokTopAdsDetailParams {
  "material_id": string;
}

export type TiktokTopAdsFiltersResponse = CrawloraResponse<ModelPopulartrendTopAdsFiltersResponseDoc>;
export interface TiktokTopAdsFiltersParams {
}

export type TiktokTopAdsListResponse = CrawloraResponse<ModelPopulartrendTopAdsListResponseDoc>;
export interface TiktokTopAdsListParams {
  "period"?: "7" | "30" | "180";
  "page"?: number;
  "limit"?: number;
  "order_by"?: "for_you" | "impression" | "ctr" | "play_2s_rate" | "play_6s_rate" | "cvr" | "like";
  "country_code"?: string;
  "keyword"?: string;
  "industry"?: string;
  "objective"?: string;
  "ad_language"?: string;
  "pattern_label"?: string;
  "duration"?: "time-2" | "time-3" | "time-4" | "time-5" | "time-6" | "time-7";
  "like"?: "1" | "2" | "3" | "4" | "5";
  "ad_format"?: "1" | "2";
}

export type TiktokTopAdsLocationInfoResponse = CrawloraResponse<ModelPopulartrendTopAdsLocationInfoResponseDoc>;
export interface TiktokTopAdsLocationInfoParams {
  "module"?: number;
}

export type TiktokTopAdsLocationsResponse = CrawloraResponse<ModelPopulartrendTopAdsLocationsResponseDoc>;
export interface TiktokTopAdsLocationsParams {
}

export type TiktokTopAdsRecommendResponse = CrawloraResponse<ModelPopulartrendTopAdsRecommendResponseDoc>;
export interface TiktokTopAdsRecommendParams {
  "material_id": string;
  "page"?: number;
  "limit"?: number;
}

export type TiktokTopAdsSafetyResponse = CrawloraResponse<ModelPopulartrendTopAdsSafetyResponseDoc>;
export interface TiktokTopAdsSafetyParams {
}

export type TiktokTopAdsSpotlightResponse = CrawloraResponse<ModelPopulartrendTopAdsSpotlightResponseDoc>;
export interface TiktokTopAdsSpotlightParams {
  "page"?: number;
  "limit"?: number;
}

export type TiktokTopAdsSuggestionsResponse = CrawloraResponse<ModelPopulartrendTopAdsSuggestionsResponseDoc>;
export interface TiktokTopAdsSuggestionsParams {
  "count"?: number;
  "scenario"?: number;
}

export type TiktokTrendingResponse = CrawloraResponse<ModelTiktokTrendingResponseDoc>;
export interface TiktokTrendingParams {
}

export interface TiktokService {
  category<T = TiktokCategoryResponse>(params?: TiktokCategoryParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  videoComments<T = TiktokVideoCommentsResponse>(params: TiktokVideoCommentsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  creativeCenterHashtags<T = TiktokCreativeCenterHashtagsResponse>(params: TiktokCreativeCenterHashtagsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  creativeCenterVideos<T = TiktokCreativeCenterVideosResponse>(params: TiktokCreativeCenterVideosParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  explore<T = TiktokExploreResponse>(params: TiktokExploreParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  challenge<T = TiktokChallengeResponse>(params: TiktokChallengeParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  challengeList<T = TiktokChallengeListResponse>(params: TiktokChallengeListParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  popularTrendCountryIndustryMeta<T = TiktokPopularTrendCountryIndustryMetaResponse>(params?: TiktokPopularTrendCountryIndustryMetaParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  post<T = TiktokPostResponse>(params: TiktokPostParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  profilePost<T = TiktokProfilePostResponse>(params: TiktokProfilePostParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  profile<T = TiktokProfileResponse>(params: TiktokProfileParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  search<T = TiktokSearchResponse>(params: TiktokSearchParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  searchHashtag<T = TiktokSearchHashtagResponse>(params: TiktokSearchHashtagParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  searchUser<T = TiktokSearchUserResponse>(params: TiktokSearchUserParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  topAdsAnalysis<T = TiktokTopAdsAnalysisResponse>(params: TiktokTopAdsAnalysisParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  topAdsDetail<T = TiktokTopAdsDetailResponse>(params: TiktokTopAdsDetailParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  topAdsFilters<T = TiktokTopAdsFiltersResponse>(params?: TiktokTopAdsFiltersParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  topAdsList<T = TiktokTopAdsListResponse>(params?: TiktokTopAdsListParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  topAdsLocationInfo<T = TiktokTopAdsLocationInfoResponse>(params?: TiktokTopAdsLocationInfoParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  topAdsLocations<T = TiktokTopAdsLocationsResponse>(params?: TiktokTopAdsLocationsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  topAdsRecommend<T = TiktokTopAdsRecommendResponse>(params: TiktokTopAdsRecommendParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  topAdsSafety<T = TiktokTopAdsSafetyResponse>(params?: TiktokTopAdsSafetyParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  topAdsSpotlight<T = TiktokTopAdsSpotlightResponse>(params?: TiktokTopAdsSpotlightParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  topAdsSuggestions<T = TiktokTopAdsSuggestionsResponse>(params?: TiktokTopAdsSuggestionsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  trending<T = TiktokTrendingResponse>(params?: TiktokTrendingParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
}

export interface CrawloraGeneratedGroups {
  tiktok: TiktokService;
}

export interface OperationParamsMap {
  "tiktok-category": TiktokCategoryParams;
  "tiktok-video-comments": TiktokVideoCommentsParams;
  "tiktok-creative-center-hashtags": TiktokCreativeCenterHashtagsParams;
  "tiktok-creative-center-videos": TiktokCreativeCenterVideosParams;
  "tiktok-explore": TiktokExploreParams;
  "tiktok-challenge": TiktokChallengeParams;
  "tiktok-challenge-list": TiktokChallengeListParams;
  "tiktok-popular-trend-country-industry-meta": TiktokPopularTrendCountryIndustryMetaParams;
  "tiktok-post": TiktokPostParams;
  "tiktok-profile-post": TiktokProfilePostParams;
  "tiktok-profile": TiktokProfileParams;
  "tiktok-search": TiktokSearchParams;
  "tiktok-search-hashtag": TiktokSearchHashtagParams;
  "tiktok-search-user": TiktokSearchUserParams;
  "tiktok-top-ads-analysis": TiktokTopAdsAnalysisParams;
  "tiktok-top-ads-detail": TiktokTopAdsDetailParams;
  "tiktok-top-ads-filters": TiktokTopAdsFiltersParams;
  "tiktok-top-ads-list": TiktokTopAdsListParams;
  "tiktok-top-ads-location-info": TiktokTopAdsLocationInfoParams;
  "tiktok-top-ads-locations": TiktokTopAdsLocationsParams;
  "tiktok-top-ads-recommend": TiktokTopAdsRecommendParams;
  "tiktok-top-ads-safety": TiktokTopAdsSafetyParams;
  "tiktok-top-ads-spotlight": TiktokTopAdsSpotlightParams;
  "tiktok-top-ads-suggestions": TiktokTopAdsSuggestionsParams;
  "tiktok-trending": TiktokTrendingParams;
}

export interface OperationResponseMap {
  "tiktok-category": TiktokCategoryResponse;
  "tiktok-video-comments": TiktokVideoCommentsResponse;
  "tiktok-creative-center-hashtags": TiktokCreativeCenterHashtagsResponse;
  "tiktok-creative-center-videos": TiktokCreativeCenterVideosResponse;
  "tiktok-explore": TiktokExploreResponse;
  "tiktok-challenge": TiktokChallengeResponse;
  "tiktok-challenge-list": TiktokChallengeListResponse;
  "tiktok-popular-trend-country-industry-meta": TiktokPopularTrendCountryIndustryMetaResponse;
  "tiktok-post": TiktokPostResponse;
  "tiktok-profile-post": TiktokProfilePostResponse;
  "tiktok-profile": TiktokProfileResponse;
  "tiktok-search": TiktokSearchResponse;
  "tiktok-search-hashtag": TiktokSearchHashtagResponse;
  "tiktok-search-user": TiktokSearchUserResponse;
  "tiktok-top-ads-analysis": TiktokTopAdsAnalysisResponse;
  "tiktok-top-ads-detail": TiktokTopAdsDetailResponse;
  "tiktok-top-ads-filters": TiktokTopAdsFiltersResponse;
  "tiktok-top-ads-list": TiktokTopAdsListResponse;
  "tiktok-top-ads-location-info": TiktokTopAdsLocationInfoResponse;
  "tiktok-top-ads-locations": TiktokTopAdsLocationsResponse;
  "tiktok-top-ads-recommend": TiktokTopAdsRecommendResponse;
  "tiktok-top-ads-safety": TiktokTopAdsSafetyResponse;
  "tiktok-top-ads-spotlight": TiktokTopAdsSpotlightResponse;
  "tiktok-top-ads-suggestions": TiktokTopAdsSuggestionsResponse;
  "tiktok-trending": TiktokTrendingResponse;
}

export interface OperationRequiredParamsMap {
  "tiktok-category": false;
  "tiktok-video-comments": true;
  "tiktok-creative-center-hashtags": true;
  "tiktok-creative-center-videos": true;
  "tiktok-explore": true;
  "tiktok-challenge": true;
  "tiktok-challenge-list": true;
  "tiktok-popular-trend-country-industry-meta": false;
  "tiktok-post": true;
  "tiktok-profile-post": true;
  "tiktok-profile": true;
  "tiktok-search": true;
  "tiktok-search-hashtag": true;
  "tiktok-search-user": true;
  "tiktok-top-ads-analysis": true;
  "tiktok-top-ads-detail": true;
  "tiktok-top-ads-filters": false;
  "tiktok-top-ads-list": false;
  "tiktok-top-ads-location-info": false;
  "tiktok-top-ads-locations": false;
  "tiktok-top-ads-recommend": true;
  "tiktok-top-ads-safety": false;
  "tiktok-top-ads-spotlight": false;
  "tiktok-top-ads-suggestions": false;
  "tiktok-trending": false;
}

export type OperationId = keyof OperationParamsMap;

export type OperationRequestArgs<I extends OperationId> =
  OperationRequiredParamsMap[I] extends true
    ? [params: OperationParamsMap[I], options?: import('./index.js').CrawloraRequestOptions]
    : [params?: OperationParamsMap[I], options?: import('./index.js').CrawloraRequestOptions];

export type OperationIdLiteral =
  | "tiktok-category"
  | "tiktok-video-comments"
  | "tiktok-creative-center-hashtags"
  | "tiktok-creative-center-videos"
  | "tiktok-explore"
  | "tiktok-challenge"
  | "tiktok-challenge-list"
  | "tiktok-popular-trend-country-industry-meta"
  | "tiktok-post"
  | "tiktok-profile-post"
  | "tiktok-profile"
  | "tiktok-search"
  | "tiktok-search-hashtag"
  | "tiktok-search-user"
  | "tiktok-top-ads-analysis"
  | "tiktok-top-ads-detail"
  | "tiktok-top-ads-filters"
  | "tiktok-top-ads-list"
  | "tiktok-top-ads-location-info"
  | "tiktok-top-ads-locations"
  | "tiktok-top-ads-recommend"
  | "tiktok-top-ads-safety"
  | "tiktok-top-ads-spotlight"
  | "tiktok-top-ads-suggestions"
  | "tiktok-trending";

export declare const OperationIds: Readonly<{
  TiktokCategory: "tiktok-category";
  TiktokChallenge: "tiktok-challenge";
  TiktokChallengeList: "tiktok-challenge-list";
  TiktokCreativeCenterHashtags: "tiktok-creative-center-hashtags";
  TiktokCreativeCenterVideos: "tiktok-creative-center-videos";
  TiktokExplore: "tiktok-explore";
  TiktokPopularTrendCountryIndustryMeta: "tiktok-popular-trend-country-industry-meta";
  TiktokPost: "tiktok-post";
  TiktokProfile: "tiktok-profile";
  TiktokProfilePost: "tiktok-profile-post";
  TiktokSearch: "tiktok-search";
  TiktokSearchHashtag: "tiktok-search-hashtag";
  TiktokSearchUser: "tiktok-search-user";
  TiktokTopAdsAnalysis: "tiktok-top-ads-analysis";
  TiktokTopAdsDetail: "tiktok-top-ads-detail";
  TiktokTopAdsFilters: "tiktok-top-ads-filters";
  TiktokTopAdsList: "tiktok-top-ads-list";
  TiktokTopAdsLocationInfo: "tiktok-top-ads-location-info";
  TiktokTopAdsLocations: "tiktok-top-ads-locations";
  TiktokTopAdsRecommend: "tiktok-top-ads-recommend";
  TiktokTopAdsSafety: "tiktok-top-ads-safety";
  TiktokTopAdsSpotlight: "tiktok-top-ads-spotlight";
  TiktokTopAdsSuggestions: "tiktok-top-ads-suggestions";
  TiktokTrending: "tiktok-trending";
  TiktokVideoComments: "tiktok-video-comments";
}>;
