// Code generated by the Crawlora platform SDK generator. DO NOT EDIT.

package tiktok

import (
	"context"
	"sort"
)

type parameterDefinition struct {
	Name             string
	In               string
	Type             string
	CollectionFormat string
	Required         bool
	Enum             []string
}

type operationDefinition struct {
	Method      string
	Path        string
	PathParams  []string
	QueryParams []parameterDefinition
	Produces    []string
	Security    []string
}

var operations = map[string]operationDefinition{
	"tiktok-category":                            operationDefinition{Method: "GET", Path: "/tiktok/category", PathParams: nil, QueryParams: nil, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"tiktok-video-comments":                      operationDefinition{Method: "GET", Path: "/tiktok/comments", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "aweme_id", In: "query", Type: "string", Required: true}, parameterDefinition{Name: "cursor", In: "query", Type: "integer"}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"tiktok-creative-center-hashtags":            operationDefinition{Method: "GET", Path: "/tiktok/creative-center/hashtags", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "country_code", In: "query", Type: "string", Required: true}, parameterDefinition{Name: "period", In: "query", Type: "integer", Enum: []string{"7", "30"}}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"tiktok-creative-center-videos":              operationDefinition{Method: "GET", Path: "/tiktok/creative-center/videos", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "country_code", In: "query", Type: "string", Required: true}, parameterDefinition{Name: "period", In: "query", Type: "integer", Enum: []string{"7", "30"}}, parameterDefinition{Name: "sort_by", In: "query", Type: "string", Enum: []string{"views", "engagement", "six_second_views"}}, parameterDefinition{Name: "content_label_id", In: "query", Type: "string"}, parameterDefinition{Name: "organic_only", In: "query", Type: "boolean"}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"tiktok-explore":                             operationDefinition{Method: "GET", Path: "/tiktok/explore/{id}", PathParams: []string{"id"}, QueryParams: nil, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"tiktok-challenge":                           operationDefinition{Method: "GET", Path: "/tiktok/hashtag/{name}", PathParams: []string{"name"}, QueryParams: nil, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"tiktok-challenge-list":                      operationDefinition{Method: "GET", Path: "/tiktok/hashtags", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "id", In: "query", Type: "string", Required: true}, parameterDefinition{Name: "cursor", In: "query", Type: "integer"}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"tiktok-popular-trend-country-industry-meta": operationDefinition{Method: "GET", Path: "/tiktok/popular-trend/country-industry-meta", PathParams: nil, QueryParams: nil, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"tiktok-post":                                operationDefinition{Method: "GET", Path: "/tiktok/post/{id}", PathParams: []string{"id"}, QueryParams: nil, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"tiktok-profile-post":                        operationDefinition{Method: "GET", Path: "/tiktok/posts", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "secUid", In: "query", Type: "string", Required: true}, parameterDefinition{Name: "cursor", In: "query", Type: "integer"}, parameterDefinition{Name: "sort_type", In: "query", Type: "integer", Enum: []string{"0", "1", "2"}}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"tiktok-profile":                             operationDefinition{Method: "GET", Path: "/tiktok/profile/{handler}", PathParams: []string{"handler"}, QueryParams: nil, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"tiktok-search":                              operationDefinition{Method: "GET", Path: "/tiktok/search", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "keyword", In: "query", Type: "string", Required: true}, parameterDefinition{Name: "cursor", In: "query", Type: "integer"}, parameterDefinition{Name: "count", In: "query", Type: "integer"}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"tiktok-search-hashtag":                      operationDefinition{Method: "GET", Path: "/tiktok/search/hashtag", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "keyword", In: "query", Type: "string", Required: true}, parameterDefinition{Name: "cursor", In: "query", Type: "integer"}, parameterDefinition{Name: "count", In: "query", Type: "integer"}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"tiktok-search-user":                         operationDefinition{Method: "GET", Path: "/tiktok/search/user", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "keyword", In: "query", Type: "string", Required: true}, parameterDefinition{Name: "cursor", In: "query", Type: "integer"}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"tiktok-top-ads-analysis":                    operationDefinition{Method: "GET", Path: "/tiktok/top-ads/analysis", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "material_id", In: "query", Type: "string", Required: true}, parameterDefinition{Name: "metric", In: "query", Type: "string", Enum: []string{"retain_ctr", "retain_cvr", "click_cnt", "convert_cnt", "play_retain_cnt"}}, parameterDefinition{Name: "period_type", In: "query", Type: "integer", Enum: []string{"7", "30", "180"}}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"tiktok-top-ads-detail":                      operationDefinition{Method: "GET", Path: "/tiktok/top-ads/detail", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "material_id", In: "query", Type: "string", Required: true}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"tiktok-top-ads-filters":                     operationDefinition{Method: "GET", Path: "/tiktok/top-ads/filters", PathParams: nil, QueryParams: nil, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"tiktok-top-ads-list":                        operationDefinition{Method: "GET", Path: "/tiktok/top-ads/list", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "period", In: "query", Type: "integer", Enum: []string{"7", "30", "180"}}, parameterDefinition{Name: "page", In: "query", Type: "integer"}, parameterDefinition{Name: "limit", In: "query", Type: "integer"}, parameterDefinition{Name: "order_by", In: "query", Type: "string", Enum: []string{"for_you", "impression", "ctr", "play_2s_rate", "play_6s_rate", "cvr", "like"}}, parameterDefinition{Name: "country_code", In: "query", Type: "string"}, parameterDefinition{Name: "keyword", In: "query", Type: "string"}, parameterDefinition{Name: "industry", In: "query", Type: "string"}, parameterDefinition{Name: "objective", In: "query", Type: "string"}, parameterDefinition{Name: "ad_language", In: "query", Type: "string"}, parameterDefinition{Name: "pattern_label", In: "query", Type: "string"}, parameterDefinition{Name: "duration", In: "query", Type: "string", Enum: []string{"time-2", "time-3", "time-4", "time-5", "time-6", "time-7"}}, parameterDefinition{Name: "like", In: "query", Type: "string", Enum: []string{"1", "2", "3", "4", "5"}}, parameterDefinition{Name: "ad_format", In: "query", Type: "string", Enum: []string{"1", "2"}}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"tiktok-top-ads-location-info":               operationDefinition{Method: "GET", Path: "/tiktok/top-ads/location-info", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "module", In: "query", Type: "integer"}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"tiktok-top-ads-locations":                   operationDefinition{Method: "GET", Path: "/tiktok/top-ads/locations", PathParams: nil, QueryParams: nil, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"tiktok-top-ads-recommend":                   operationDefinition{Method: "GET", Path: "/tiktok/top-ads/recommend", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "material_id", In: "query", Type: "string", Required: true}, parameterDefinition{Name: "page", In: "query", Type: "integer"}, parameterDefinition{Name: "limit", In: "query", Type: "integer"}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"tiktok-top-ads-safety":                      operationDefinition{Method: "GET", Path: "/tiktok/top-ads/safety", PathParams: nil, QueryParams: nil, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"tiktok-top-ads-spotlight":                   operationDefinition{Method: "GET", Path: "/tiktok/top-ads/spotlight", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "page", In: "query", Type: "integer"}, parameterDefinition{Name: "limit", In: "query", Type: "integer"}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"tiktok-top-ads-suggestions":                 operationDefinition{Method: "GET", Path: "/tiktok/top-ads/suggestions", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "count", In: "query", Type: "integer"}, parameterDefinition{Name: "scenario", In: "query", Type: "integer"}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"tiktok-trending":                            operationDefinition{Method: "GET", Path: "/tiktok/trending", PathParams: nil, QueryParams: nil, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
}

// OperationCount reports how many selected-platform operations this module exposes.
const OperationCount = 25

// OperationIDs returns the selected operation IDs in stable sorted order.
func OperationIDs() []string {
	ids := make([]string, 0, len(operations))
	for id := range operations {
		ids = append(ids, id)
	}
	sort.Strings(ids)
	return ids
}

// Category calls the tiktok-category operation.
func (c *Client) Category(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "tiktok-category", params)
}

// VideoComments calls the tiktok-video-comments operation.
func (c *Client) VideoComments(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "tiktok-video-comments", params)
}

// CreativeCenterHashtags calls the tiktok-creative-center-hashtags operation.
func (c *Client) CreativeCenterHashtags(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "tiktok-creative-center-hashtags", params)
}

// CreativeCenterVideos calls the tiktok-creative-center-videos operation.
func (c *Client) CreativeCenterVideos(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "tiktok-creative-center-videos", params)
}

// Explore calls the tiktok-explore operation.
func (c *Client) Explore(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "tiktok-explore", params)
}

// Challenge calls the tiktok-challenge operation.
func (c *Client) Challenge(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "tiktok-challenge", params)
}

// ChallengeList calls the tiktok-challenge-list operation.
func (c *Client) ChallengeList(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "tiktok-challenge-list", params)
}

// PopularTrendCountryIndustryMeta calls the tiktok-popular-trend-country-industry-meta operation.
func (c *Client) PopularTrendCountryIndustryMeta(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "tiktok-popular-trend-country-industry-meta", params)
}

// Post calls the tiktok-post operation.
func (c *Client) Post(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "tiktok-post", params)
}

// ProfilePost calls the tiktok-profile-post operation.
func (c *Client) ProfilePost(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "tiktok-profile-post", params)
}

// Profile calls the tiktok-profile operation.
func (c *Client) Profile(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "tiktok-profile", params)
}

// Search calls the tiktok-search operation.
func (c *Client) Search(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "tiktok-search", params)
}

// SearchHashtag calls the tiktok-search-hashtag operation.
func (c *Client) SearchHashtag(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "tiktok-search-hashtag", params)
}

// SearchUser calls the tiktok-search-user operation.
func (c *Client) SearchUser(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "tiktok-search-user", params)
}

// TopAdsAnalysis calls the tiktok-top-ads-analysis operation.
func (c *Client) TopAdsAnalysis(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "tiktok-top-ads-analysis", params)
}

// TopAdsDetail calls the tiktok-top-ads-detail operation.
func (c *Client) TopAdsDetail(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "tiktok-top-ads-detail", params)
}

// TopAdsFilters calls the tiktok-top-ads-filters operation.
func (c *Client) TopAdsFilters(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "tiktok-top-ads-filters", params)
}

// TopAdsList calls the tiktok-top-ads-list operation.
func (c *Client) TopAdsList(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "tiktok-top-ads-list", params)
}

// TopAdsLocationInfo calls the tiktok-top-ads-location-info operation.
func (c *Client) TopAdsLocationInfo(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "tiktok-top-ads-location-info", params)
}

// TopAdsLocations calls the tiktok-top-ads-locations operation.
func (c *Client) TopAdsLocations(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "tiktok-top-ads-locations", params)
}

// TopAdsRecommend calls the tiktok-top-ads-recommend operation.
func (c *Client) TopAdsRecommend(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "tiktok-top-ads-recommend", params)
}

// TopAdsSafety calls the tiktok-top-ads-safety operation.
func (c *Client) TopAdsSafety(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "tiktok-top-ads-safety", params)
}

// TopAdsSpotlight calls the tiktok-top-ads-spotlight operation.
func (c *Client) TopAdsSpotlight(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "tiktok-top-ads-spotlight", params)
}

// TopAdsSuggestions calls the tiktok-top-ads-suggestions operation.
func (c *Client) TopAdsSuggestions(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "tiktok-top-ads-suggestions", params)
}

// Trending calls the tiktok-trending operation.
func (c *Client) Trending(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "tiktok-trending", params)
}
